# Generated by Django 4.2.16 on 2024-11-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ctadescription",
            name="cta_button_link",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AddField(
            model_name="ctadescription",
            name="cta_button_text",
            field=models.CharField(default="", max_length=50),
        ),
    ]
