# Generated by Django 4.2.16 on 2024-11-13 07:03

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_ctadescription_side_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(old_name="ContactInfo", new_name="SiteInfo",),
        migrations.AlterField(
            model_name="howwecanhelpsection",
            name="icon",
            field=models.FileField(
                upload_to="help", validators=[app.models.validate_svg_or_image]
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.faqcategory",
            ),
            preserve_default=False,
        ),
    ]
