# Generated by Django 4.2.16 on 2024-11-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_faqcategory_rename_contactinfo_siteinfo_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="CoreServices", new_name="CoreService",),
    ]
