# Generated by Django 4.2.16 on 2024-11-13 14:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_coreservices_coreservice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
