# Generated by Django 4.2.16 on 2024-11-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_faq_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq", name="question", field=models.CharField(max_length=400),
        ),
    ]
