# Generated by Django 4.2.16 on 2024-11-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_blogimage_blogcomment_post_blogpost_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinfo",
            name="airbnb_link",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AddField(
            model_name="siteinfo",
            name="booking_link",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AddField(
            model_name="siteinfo",
            name="triadvisor_link",
            field=models.CharField(default="", max_length=300),
        ),
    ]
