# Generated by Django 4.2.16 on 2024-11-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_siteinfo_airbnb_link_siteinfo_booking_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost", name="slug", field=models.SlugField(default=""),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="heading",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
