# Generated by Django 4.2.16 on 2024-11-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_blogpost_slug_alter_blogpost_heading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost", name="slug", field=models.SlugField(default="#"),
        ),
    ]
