# Generated by Django 4.2.16 on 2024-11-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_blogpost_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(default="13708027"),
        ),
    ]
