# Generated by Django 4.2.16 on 2024-11-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_alter_blogpost_slug"),
    ]

    operations = [
        migrations.RemoveField(model_name="blogpost", name="slug",),
        migrations.AddField(
            model_name="blogcomment",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
