# Generated by Django 4.2.16 on 2024-11-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_contactinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentBookingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
