# Generated by Django 4.2.16 on 2024-11-23 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_remove_siteinfo_twitter_link_siteinfo_linkedin_link_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="siteinfo",
            old_name="triadvisor_link",
            new_name="tripadvisor_link",
        ),
    ]
